export const stateMapping = {
  'jammu-kashmir': { dbName: 'jammu & kashmir', title: 'Jammu & Kashmir', desc: 'Crafts of the Valley. Famed for ultra-fine Pashmina cashmere looms, walnut woodcarvings, and Kashmiri paper mache.' },
  'ladakh': { dbName: 'ladakh', title: 'Ladakh', desc: 'The Land of High Passes. Known for Pashmina wool crafts, Thangka scroll paintings, and traditional carpets.' },
  'himachal-pradesh': { dbName: 'himachal pradesh', title: 'Himachal Pradesh', desc: 'Mountain Heritage. Celebrated for Kullu handloom shawls, Chamba Rumal embroidery, and Kangra miniature paintings.' },
  'punjab': { dbName: 'punjab', title: 'Punjab', desc: 'Colors of Punjab. Renowned for vibrant geometric Phulkari floral hand embroideries.' },
  'chandigarh': { dbName: 'chandigarh', title: 'Chandigarh', desc: 'The City Beautiful. Known for Rock Garden recycled art and Phulkari textile traditions.' },
  'uttarakhand': { dbName: 'uttarakhand', title: 'Uttarakhand', desc: 'Devbhoomi Heritage. Famous for Aipan folk art, Ringal bamboo craft, and woolen textiles.' },
  'haryana': { dbName: 'haryana', title: 'Haryana', desc: 'Folk Traditions. Known for Phulkari embroidery, traditional pottery, and handloom durries.' },
  'delhi': { dbName: 'delhi', title: 'Delhi', desc: 'Capital Crafts. Renowned for Zardozi embroidery, Meenakari jewelry, and traditional block printing.' },
  'rajasthan': { dbName: 'rajasthan', title: 'Rajasthan', desc: 'Land of Royals. Famed for cobalt-glazed blue clay pottery, Sanganeri block-print quilts, and Bandhani tie-dye.' },
  'uttar-pradesh': { dbName: 'uttar pradesh', title: 'Uttar Pradesh', desc: 'Ganga-Yamuna Weaves. Renowned for gold-brocade Banarasi sarees and Lucknowi Chikankari shadow work.' },
  'uttarpradesh': { dbName: 'uttar pradesh', title: 'Uttar Pradesh', desc: 'Ganga-Yamuna Weaves. Renowned for gold-brocade Banarasi sarees and Lucknowi Chikankari shadow work.' },
  'gujarat': { dbName: 'gujarat', title: 'Gujarat', desc: 'Colors of Patan. Renowned for Patan Patola double-ikat sarees and Lippan mud-relief art.' },
  'maharashtra': { dbName: 'maharashtra', title: 'Maharashtra', desc: 'Maharashtrian Royal Linens. Famed for Yeola Paithani sarees and Warli folk paintings.' },
  'goa': { dbName: 'goa', title: 'Goa', desc: 'Coastal Craft. Known for Kunbi weaving, terracotta pottery, and crochet lace craft.' },
  'madhya-pradesh': { dbName: 'madhya pradesh', title: 'Madhya Pradesh', desc: 'Central Loom Traditions. Famed for delicate Chanderi handlooms and Bagh block prints.' },
  'madhyapradesh': { dbName: 'madhya pradesh', title: 'Madhya Pradesh', desc: 'Central Loom Traditions. Famed for delicate Chanderi handlooms and Bagh block prints.' },
  'chhattisgarh': { dbName: 'chhattisgarh', title: 'Chhattisgarh', desc: 'Tribal Art Heritage. Famous for bell metal (Dokra) craft, Kosa silk, and bamboo crafts.' },
  'bihar': { dbName: 'bihar', title: 'Bihar', desc: 'Ancient Art Traditions. Celebrated for Madhubani folk paintings, Sujani embroidery, and Sikki grass craft.' },
  'jharkhand': { dbName: 'jharkhand', title: 'Jharkhand', desc: 'Tribal Craft Heritage. Known for Dokra metal casting, Paitkar scroll paintings, and Sohrai wall art.' },
  'west-bengal': { dbName: 'west bengal', title: 'West Bengal', desc: 'Artistry of Bengal. Renowned for intricate Kantha embroidery, tussar silk, and Santiniketan embossed leather crafts.' },
  'westbengal': { dbName: 'west bengal', title: 'West Bengal', desc: 'Artistry of Bengal. Renowned for intricate Kantha embroidery, tussar silk, and Santiniketan embossed leather crafts.' },
  'odisha': { dbName: 'odisha', title: 'Odisha', desc: 'Odisha Ikat. Famous for Sambalpuri tie-dye handlooms and Pattachitra folk canvases.' },
  'sikkim': { dbName: 'sikkim', title: 'Sikkim', desc: 'Himalayan Heritage. Known for Thangka paintings, handmade carpets, and bamboo craft.' },
  'assam': { dbName: 'assam', title: 'Assam', desc: 'Assamese Golden Threads. Celebrated for golden-yellow Muga silks and fine bamboo weaving.' },
  'arunachal-pradesh': { dbName: 'arunachal pradesh', title: 'Arunachal Pradesh', desc: 'Eastern Himalayan Crafts. Known for Thangka paintings, carpet weaving, and bamboo/cane work.' },
  'nagaland': { dbName: 'nagaland', title: 'Nagaland', desc: 'Warrior Heritage. Famous for Naga shawls, wood carving, and intricate bead jewelry.' },
  'manipur': { dbName: 'manipur', title: 'Manipur', desc: 'Jewel of the Northeast. Known for Kauna reed craft, Moirang Phee handlooms, and Longpi pottery.' },
  'mizoram': { dbName: 'mizoram', title: 'Mizoram', desc: 'Land of the Blue Mountains. Famous for Puan weaving, bamboo craft, and cane furniture.' },
  'tripura': { dbName: 'tripura', title: 'Tripura', desc: 'Royal Weaving Heritage. Known for Rignai and Risa weaving, bamboo and cane craft.' },
  'meghalaya': { dbName: 'meghalaya', title: 'Meghalaya', desc: 'Abode of Clouds. Celebrated for cane and bamboo craft, Eri silk, and traditional weaving.' },
  'karnataka': { dbName: 'karnataka', title: 'Karnataka', desc: 'Heritage of the Deccan. Known for Channapatna wood lacquerware, Shimoga sandalwood carvings, and royal Mysore crepe silks.' },
  'kerala': { dbName: 'kerala', title: 'Kerala', desc: 'Land of Handlooms. Celebrated for Aranmula metal-alloy mirrors and golden-bordered Balaramapuram Kasavu weaves.' },
  'tamilnadu': { dbName: 'tamil nadu', title: 'Tamil Nadu', desc: 'Legacy of Temples. Celebrated for heavy Kanchipuram mulberry silk brocades and embossed 22k gold Tanjore paintings.' },
  'tamil-nadu': { dbName: 'tamil nadu', title: 'Tamil Nadu', desc: 'Legacy of Temples. Celebrated for heavy Kanchipuram mulberry silk brocades and embossed 22k gold Tanjore paintings.' },
  'telangana': { dbName: 'telangana', title: 'Telangana', desc: 'Deccan Heritage. Famous for Nirmal paintings, Pochampally Ikat weaving, and Bidri metalware.' },
  'andhra-pradesh': { dbName: 'andhra pradesh', title: 'Andhra Pradesh', desc: 'Coastal Craft Legacy. Known for Kalamkari hand-painted textiles, Kondapalli wooden toys, and Etikoppaka lacquerware.' },
  'puducherry': { dbName: 'puducherry', title: 'Puducherry', desc: 'French Quarter Crafts. Known for pottery, handloom textiles, and leather goods.' },
  'lakshadweep': { dbName: 'lakshadweep', title: 'Lakshadweep', desc: 'Island Crafts. Famous for coir craft, shell jewelry, and traditional boat building.' },
  'andaman-nicobar': { dbName: 'andaman & nicobar', title: 'Andaman & Nicobar Islands', desc: 'Island Heritage. Known for shell craft, Nicobari weaving, and coconut shell art.' },
  'dadra-nagar-haveli': { dbName: 'dadra & nagar haveli', title: 'Dadra & Nagar Haveli and Daman & Diu', desc: 'Tribal Craft. Known for Warli folk paintings and traditional weaving.' },
};
